// Writes src/core/model-config-schema.generated.ts: the schema of models.json, as model-config-schema.ts builds it with
// TypeBox, in plain JSON Schema. Run it after changing model-config-schema.ts (test/model-config-schema.test.ts checks).
//   bun scripts/generate-model-config-schema.ts
import { spawnSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { buildModelsConfigSchemas } from "../src/core/model-config-schema.ts";

const schema = JSON.stringify(buildModelsConfigSchemas().ModelsConfigSchema, null, "\t");
const source = `// Generated by scripts/generate-model-config-schema.ts from model-config-schema.ts: do not edit.
// The schema of models.json as plain JSON Schema, which costs nothing to build at start, unlike TypeBox's Type.* calls.

let schema: object | undefined;

export function modelsConfigSchema(): object {
	schema ??= ${schema.replace(/\n/g, "\n\t")};
	return schema;
}
`;
const out = fileURLToPath(new URL("../src/core/model-config-schema.generated.ts", import.meta.url));
writeFileSync(out, source);
// In the repository's style, as \`npm run check\` wants it.
const biome = spawnSync("npx", ["biome", "format", "--write", out], { stdio: "inherit" });
if (biome.status !== 0) process.exit(biome.status ?? 1);
