# shellcheck shell=bash
# Shared helpers for the Pi-Bolt scripts. Sourced, not run.
set -euo pipefail

PIBOLT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
# Where sources, toolchains and builds live; override with PIBOLT_WORK.
PIBOLT_WORK="${PIBOLT_WORK:-$PIBOLT_ROOT/.work}"
# The Pi to build: this repository, which is a fork of Pi. Override with PIBOLT_PI or --pi.
PIBOLT_PI="${PIBOLT_PI:-$PIBOLT_ROOT}"

log() { printf '\033[1;36m==>\033[0m %s\n' "$*" >&2; }
warn() { printf '\033[1;33mwarning:\033[0m %s\n' "$*" >&2; }
die() { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

need() { command -v "$1" >/dev/null 2>&1 || die "'$1' is required but not installed"; }

# source_field <component> <field>: a value from sources.json.
source_field() {
	python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))[sys.argv[2]].get(sys.argv[3], ""))' "$PIBOLT_ROOT/sources.json" "$1" "$2"
}

# The Bun runtime with the ahead-of-time engine: an explicit PIBOLT_BUN, else the one build-runtime.sh made.
runtime_bun() {
	local bun="${PIBOLT_BUN:-$PIBOLT_WORK/runtime/bun}"
	[ -x "$bun" ] || die "no Pi-Bolt runtime at $bun: run scripts/build-runtime.sh, or set PIBOLT_BUN"
	printf '%s\n' "$bun"
}

# Pi's coding-agent package in a Pi checkout that has been built, and its version.
pi_agent_dir() {
	local agent
	agent="$(realpath "$1")/packages/coding-agent"
	[ -f "$agent/dist/bun/cli.js" ] || die "$agent/dist/bun/cli.js not found: build Pi first (scripts/prepare-pi.sh)"
	printf '%s\n' "$agent"
}
pi_version() {
	python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["version"])' "$1/package.json"
}

# stage_plugins <agent dir> <manifest>: copies the manifest's folder into the Pi tree and writes the entry point that starts Pi
# with those extensions. Inside the Pi tree, the packages Pi provides to extensions (@earendil-works/pi-*, typebox) resolve to
# Pi's own modules, as they do when Pi loads an extension at run time; a copy of one inside the plugin would be a second Pi
# (duplicate classes and registries), so those are left out. Prints the entry, relative to the agent dir. The caller removes
# "$1/.pibolt-plugins" when done.
stage_plugins() {
	local agent="$1" manifest="$2" stage src
	[ -f "$manifest" ] || die "--plugins: $manifest not found"
	need rsync
	stage="$agent/.pibolt-plugins"
	src="$(dirname "$(realpath "$manifest")")"
	rm -rf "$stage" && mkdir -p "$stage"
	rsync -a --exclude .git --exclude 'node_modules/@earendil-works/pi-*' --exclude 'node_modules/typebox' "$src/" "$stage/src/"
	cat >"$stage/entry.ts" <<-EOT
		// Generated by Pi-Bolt: Pi's Bun entry (packages/coding-agent/src/bun/cli.ts), with extensions compiled in.
		import "../dist/bun/sandbox-env-setup.js";
		import "../dist/bun/runtime-setup.js";
		import { setupCli } from "../dist/cli/setup.js";
		import { main } from "../dist/main.js";
		import plugins from "./src/$(basename "$manifest")";

		setupCli();
		main(process.argv.slice(2), { extensionFactories: plugins });
	EOT
	printf '%s\n' ./.pibolt-plugins/entry.ts
}

# Pi's entry points: its Bun entry (or $1, a staged plugin entry) and the workers it starts (package.json build:binary).
pi_entries() {
	local agent="$1" entry="${2:-./dist/bun/cli.js}"
	printf '%s\n' "$entry" ./src/utils/image-resize-worker.ts
	[ -f "$agent/src/extensions/codemode/worker.ts" ] && printf '%s\n' ./src/extensions/codemode/worker.ts
	return 0
}
