// GENERATED by gen-builtins.py: built-ins with an AOT fast path, each in a loop of its own over edge-case inputs.
const out = [];
function show(v, depth = 0) {
	if (typeof v === "number") return Object.is(v, -0) ? "-0" : String(v);
	if (typeof v === "string") {
		if (v.length <= 40) return JSON.stringify(v);
		let h = 0;
		for (let i = 0; i < v.length; i++) h = (Math.imul(h, 31) + v.charCodeAt(i)) | 0;
		return `str(${v.length}:${h})`;
	}
	if (Array.isArray(v)) return depth > 2 ? "[...]" : "[" + v.slice(0, 12).map((e) => show(e, depth + 1)).join(",") + (v.length > 12 ? `,+${v.length - 12}` : "") + "]";
	if (v instanceof Map || v instanceof Set) return v.constructor.name + v.size;
	if (v && typeof v === "object") return depth > 2 ? "{...}" : "{" + Object.keys(v).slice(0, 8).map((k) => k + ":" + show(v[k], depth + 1)).join(",") + "}";
	return typeof v === "symbol" ? "sym" : String(v);
}
let at = 0;
let cells = [];
function drive(f, xs, ys) {
	cells = [];
	for (let from = 0; from < xs.length; ) {
		try {
			f(xs, ys, from);
			break;
		} catch (e) {
			cells.push("!" + e.constructor.name);
			from = at + 1;
		}
	}
	return cells.join(",");
}
function driveOne(f, xs, ys) {
	const r = [];
	for (let i = 0; i < xs.length; i++) {
		try {
			r.push(f(xs[i], ys[i % ys.length]));
		} catch (e) {
			r.push("!" + e.constructor.name);
		}
	}
	return r.join(",");
}
const copy = (a) => a.slice();
function pushedAll(a) { const b = []; for (const v of a) b.push(v); return b; }
function poppedAll(a) { const b = a.slice(); let n = 0; while (b.length) { b.pop(); n++; } return n; }
function lines(n) { let s = ""; for (let i = 1; i <= n; i++) s += i + "a\n"; return s; }
const flat = lines(14000); flat.split("\n");
const strings = ["", "a", "abc", "aXbXc", "ba", "héllo", "日本語", "\n", "a\n", lines(5), lines(14000), flat, flat.slice(3), flat.slice(0, 70000),
	"a".repeat(65534) + "\n", "a".repeat(65535) + "\n", "a".repeat(65536) + "\n", "b".repeat(70000) + "abc", "é".repeat(70000) + "a",
	" \t trim me \n", "UPPER lower İ ß", "1e3", "  42px", "0x1F", "-0", "123456789012345678901234567890", "Infinity", "zz"];
const stringArgs = [0, 1, -1, 2, 100, -100, NaN, undefined, 1.5, 65535, 70000, "1", "", "a", "X", "\n", "abc", "日", "b".repeat(100)];
const numbers = [0, -0, 1, -1, 1.5, -1.5, 2.5, -2.5, 0.49999999999999994, NaN, Infinity, -Infinity, 2 ** 31 - 1, 2 ** 31, -(2 ** 31),
	-(2 ** 31) - 1, 2 ** 32, 2 ** 53, 2 ** 53 + 2, 1e21, 5e-324, -5e-324, 1 / 3, 65, 0x10ffff, 3];
const numberArgs = [0, -0, 1, -1, 2, 0.5, NaN, Infinity, -Infinity, 2 ** 31, -3, 1e-7];
const holey = [1, , 3]; holey[10] = 4;
const arrays = [[], [1, 2, 3], [1.5, 2, NaN, -0], ["a", 2, undefined, null], holey, [[1], [2]], Array.from({ length: 70 }, (_, i) => i),
	new Array(5), [1, 2, 3].concat([4]), Object.freeze([2, 3]), ["x", "y"].map((s) => s + s)];
const arrayArgs = [[], [1], [[2]], ",", "", undefined, "-"];
const keyCases = [0, -0, NaN, "0", "a", "a".repeat(70000), {}, [], Symbol.iterator, null, undefined, 1.5, 2 ** 53];
function mapOps(k) {
	const m = new Map([[0, "zero"], ["a", "A"]]);
	m.set(k, 1); m.set(k, 2);
	return [m.get(k), m.has(k), m.get(-0), m.get(0), m.size, m.delete(k), m.has(k), m.size].map(show).join("/");
}
function setOps(k) {
	const s = new Set([0, "a"]);
	s.add(k); s.add(k);
	return [s.has(k), s.has(-0), s.size, s.delete(k), s.has(k), s.size].map(show).join("/");
}
function weakOps(k) {
	if (k === null || (typeof k !== "object" && typeof k !== "function")) return "prim";
	const wm = new WeakMap(), ws = new WeakSet();
	wm.set(k, 1); ws.add(k);
	return [wm.get(k), wm.has(k), ws.has(k), wm.delete(k), ws.delete(k), wm.has(k), ws.has(k)].map(show).join("/");
}
const dates = [new Date(0), new Date(-1), new Date(1e12 + 123), new Date(8.64e15), new Date(-8.64e15), new Date(NaN), new Date(2024, 1, 29, 23, 59, 59, 999),
	new Date("2026-03-29T01:30:00Z")];
const regexps = [/a/, /a/g, /a/y, /(\d+)/g, /^$/m, /é/u, /x*/g];
function regexpExec(r) { r.lastIndex = 0; const s = "a1a22aaa333é"; const found = []; for (let i = 0; i < 6; i++) { const m = r.exec(s); found.push(m ? m.index + ":" + m[0] : "null"); if (!m || !r.global && !r.sticky) break; } return found.join(";") + "|" + r.lastIndex; }
function regexpTest(r) { r.lastIndex = 0; const s = "xa1a"; const found = []; for (let i = 0; i < 4; i++) found.push(r.test(s), r.lastIndex); return found.join(";"); }
const objects = [{}, { a: 1, b: 2 }, Object.create(null), [1, 2], { 0: "z", a: undefined, [Symbol("s")]: 1 }, Object.assign(Object.create({ inherited: 1 }), { a: 3 }),
	new Map(), "str", Object.freeze({ a: 1 })];
function s0(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.at(y))); } }
function s0one(x, y) { return show(x.at(y)); }
out.push('s0' + " " + 'x.at(y)' + " " + drive(s0, strings, stringArgs));
out.push('s0' + "'" + drive(s0, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s0' + "1" + driveOne(s0one, strings, stringArgs));
function s1(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.charAt(y))); } }
function s1one(x, y) { return show(x.charAt(y)); }
out.push('s1' + " " + 'x.charAt(y)' + " " + drive(s1, strings, stringArgs));
out.push('s1' + "'" + drive(s1, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s1' + "1" + driveOne(s1one, strings, stringArgs));
function s2(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.charCodeAt(y))); } }
function s2one(x, y) { return show(x.charCodeAt(y)); }
out.push('s2' + " " + 'x.charCodeAt(y)' + " " + drive(s2, strings, stringArgs));
out.push('s2' + "'" + drive(s2, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s2' + "1" + driveOne(s2one, strings, stringArgs));
function s3(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.codePointAt(y))); } }
function s3one(x, y) { return show(x.codePointAt(y)); }
out.push('s3' + " " + 'x.codePointAt(y)' + " " + drive(s3, strings, stringArgs));
out.push('s3' + "'" + drive(s3, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s3' + "1" + driveOne(s3one, strings, stringArgs));
function s4(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.concat(y))); } }
function s4one(x, y) { return show(x.concat(y)); }
out.push('s4' + " " + 'x.concat(y)' + " " + drive(s4, strings, stringArgs));
out.push('s4' + "'" + drive(s4, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s4' + "1" + driveOne(s4one, strings, stringArgs));
function s5(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.concat(y, x))); } }
function s5one(x, y) { return show(x.concat(y, x)); }
out.push('s5' + " " + 'x.concat(y, x)' + " " + drive(s5, strings, stringArgs));
out.push('s5' + "'" + drive(s5, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s5' + "1" + driveOne(s5one, strings, stringArgs));
function s6(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.endsWith("a"))); } }
function s6one(x, y) { return show(x.endsWith("a")); }
out.push('s6' + " " + 'x.endsWith("a")' + " " + drive(s6, strings, stringArgs));
out.push('s6' + "'" + drive(s6, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s6' + "1" + driveOne(s6one, strings, stringArgs));
function s7(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.endsWith("\n"))); } }
function s7one(x, y) { return show(x.endsWith("\n")); }
out.push('s7' + " " + 'x.endsWith("\\n")' + " " + drive(s7, strings, stringArgs));
out.push('s7' + "'" + drive(s7, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s7' + "1" + driveOne(s7one, strings, stringArgs));
function s8(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.endsWith("abc"))); } }
function s8one(x, y) { return show(x.endsWith("abc")); }
out.push('s8' + " " + 'x.endsWith("abc")' + " " + drive(s8, strings, stringArgs));
out.push('s8' + "'" + drive(s8, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s8' + "1" + driveOne(s8one, strings, stringArgs));
function s9(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.endsWith(y))); } }
function s9one(x, y) { return show(x.endsWith(y)); }
out.push('s9' + " " + 'x.endsWith(y)' + " " + drive(s9, strings, stringArgs));
out.push('s9' + "'" + drive(s9, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s9' + "1" + driveOne(s9one, strings, stringArgs));
function s10(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.endsWith("a", y))); } }
function s10one(x, y) { return show(x.endsWith("a", y)); }
out.push('s10' + " " + 'x.endsWith("a", y)' + " " + drive(s10, strings, stringArgs));
out.push('s10' + "'" + drive(s10, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s10' + "1" + driveOne(s10one, strings, stringArgs));
function s11(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.startsWith("a"))); } }
function s11one(x, y) { return show(x.startsWith("a")); }
out.push('s11' + " " + 'x.startsWith("a")' + " " + drive(s11, strings, stringArgs));
out.push('s11' + "'" + drive(s11, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s11' + "1" + driveOne(s11one, strings, stringArgs));
function s12(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.startsWith("\n"))); } }
function s12one(x, y) { return show(x.startsWith("\n")); }
out.push('s12' + " " + 'x.startsWith("\\n")' + " " + drive(s12, strings, stringArgs));
out.push('s12' + "'" + drive(s12, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s12' + "1" + driveOne(s12one, strings, stringArgs));
function s13(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.startsWith("abc"))); } }
function s13one(x, y) { return show(x.startsWith("abc")); }
out.push('s13' + " " + 'x.startsWith("abc")' + " " + drive(s13, strings, stringArgs));
out.push('s13' + "'" + drive(s13, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s13' + "1" + driveOne(s13one, strings, stringArgs));
function s14(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.startsWith(y))); } }
function s14one(x, y) { return show(x.startsWith(y)); }
out.push('s14' + " " + 'x.startsWith(y)' + " " + drive(s14, strings, stringArgs));
out.push('s14' + "'" + drive(s14, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s14' + "1" + driveOne(s14one, strings, stringArgs));
function s15(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.startsWith("b", y))); } }
function s15one(x, y) { return show(x.startsWith("b", y)); }
out.push('s15' + " " + 'x.startsWith("b", y)' + " " + drive(s15, strings, stringArgs));
out.push('s15' + "'" + drive(s15, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s15' + "1" + driveOne(s15one, strings, stringArgs));
function s16(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.includes("a"))); } }
function s16one(x, y) { return show(x.includes("a")); }
out.push('s16' + " " + 'x.includes("a")' + " " + drive(s16, strings, stringArgs));
out.push('s16' + "'" + drive(s16, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s16' + "1" + driveOne(s16one, strings, stringArgs));
function s17(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.includes("X"))); } }
function s17one(x, y) { return show(x.includes("X")); }
out.push('s17' + " " + 'x.includes("X")' + " " + drive(s17, strings, stringArgs));
out.push('s17' + "'" + drive(s17, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s17' + "1" + driveOne(s17one, strings, stringArgs));
function s18(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.includes(y))); } }
function s18one(x, y) { return show(x.includes(y)); }
out.push('s18' + " " + 'x.includes(y)' + " " + drive(s18, strings, stringArgs));
out.push('s18' + "'" + drive(s18, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s18' + "1" + driveOne(s18one, strings, stringArgs));
function s19(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.includes("b", y))); } }
function s19one(x, y) { return show(x.includes("b", y)); }
out.push('s19' + " " + 'x.includes("b", y)' + " " + drive(s19, strings, stringArgs));
out.push('s19' + "'" + drive(s19, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s19' + "1" + driveOne(s19one, strings, stringArgs));
function s20(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.indexOf("a"))); } }
function s20one(x, y) { return show(x.indexOf("a")); }
out.push('s20' + " " + 'x.indexOf("a")' + " " + drive(s20, strings, stringArgs));
out.push('s20' + "'" + drive(s20, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s20' + "1" + driveOne(s20one, strings, stringArgs));
function s21(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.indexOf("\n"))); } }
function s21one(x, y) { return show(x.indexOf("\n")); }
out.push('s21' + " " + 'x.indexOf("\\n")' + " " + drive(s21, strings, stringArgs));
out.push('s21' + "'" + drive(s21, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s21' + "1" + driveOne(s21one, strings, stringArgs));
function s22(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.indexOf(y))); } }
function s22one(x, y) { return show(x.indexOf(y)); }
out.push('s22' + " " + 'x.indexOf(y)' + " " + drive(s22, strings, stringArgs));
out.push('s22' + "'" + drive(s22, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s22' + "1" + driveOne(s22one, strings, stringArgs));
function s23(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.indexOf("a", y))); } }
function s23one(x, y) { return show(x.indexOf("a", y)); }
out.push('s23' + " " + 'x.indexOf("a", y)' + " " + drive(s23, strings, stringArgs));
out.push('s23' + "'" + drive(s23, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s23' + "1" + driveOne(s23one, strings, stringArgs));
function s24(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.lastIndexOf("a"))); } }
function s24one(x, y) { return show(x.lastIndexOf("a")); }
out.push('s24' + " " + 'x.lastIndexOf("a")' + " " + drive(s24, strings, stringArgs));
out.push('s24' + "'" + drive(s24, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s24' + "1" + driveOne(s24one, strings, stringArgs));
function s25(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.lastIndexOf(y))); } }
function s25one(x, y) { return show(x.lastIndexOf(y)); }
out.push('s25' + " " + 'x.lastIndexOf(y)' + " " + drive(s25, strings, stringArgs));
out.push('s25' + "'" + drive(s25, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s25' + "1" + driveOne(s25one, strings, stringArgs));
function s26(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.lastIndexOf("a", y))); } }
function s26one(x, y) { return show(x.lastIndexOf("a", y)); }
out.push('s26' + " " + 'x.lastIndexOf("a", y)' + " " + drive(s26, strings, stringArgs));
out.push('s26' + "'" + drive(s26, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s26' + "1" + driveOne(s26one, strings, stringArgs));
function s27(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.localeCompare("abc"))); } }
function s27one(x, y) { return show(x.localeCompare("abc")); }
out.push('s27' + " " + 'x.localeCompare("abc")' + " " + drive(s27, strings, stringArgs));
out.push('s27' + "'" + drive(s27, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s27' + "1" + driveOne(s27one, strings, stringArgs));
function s28(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.localeCompare(y))); } }
function s28one(x, y) { return show(x.localeCompare(y)); }
out.push('s28' + " " + 'x.localeCompare(y)' + " " + drive(s28, strings, stringArgs));
out.push('s28' + "'" + drive(s28, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s28' + "1" + driveOne(s28one, strings, stringArgs));
function s29(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.match(/a+/g))); } }
function s29one(x, y) { return show(x.match(/a+/g)); }
out.push('s29' + " " + 'x.match(/a+/g)' + " " + drive(s29, strings, stringArgs));
out.push('s29' + "'" + drive(s29, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s29' + "1" + driveOne(s29one, strings, stringArgs));
function s30(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.match(/(b)(c)?/))); } }
function s30one(x, y) { return show(x.match(/(b)(c)?/)); }
out.push('s30' + " " + 'x.match(/(b)(c)?/)' + " " + drive(s30, strings, stringArgs));
out.push('s30' + "'" + drive(s30, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s30' + "1" + driveOne(s30one, strings, stringArgs));
function s31(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.replace("a", "<$&>"))); } }
function s31one(x, y) { return show(x.replace("a", "<$&>")); }
out.push('s31' + " " + 'x.replace("a", "<$&>")' + " " + drive(s31, strings, stringArgs));
out.push('s31' + "'" + drive(s31, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s31' + "1" + driveOne(s31one, strings, stringArgs));
function s32(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.replace(/X/g, "-"))); } }
function s32one(x, y) { return show(x.replace(/X/g, "-")); }
out.push('s32' + " " + 'x.replace(/X/g, "-")' + " " + drive(s32, strings, stringArgs));
out.push('s32' + "'" + drive(s32, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s32' + "1" + driveOne(s32one, strings, stringArgs));
function s33(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.replace(/(a)(b)?/, (m, p, q) => m + p + q))); } }
function s33one(x, y) { return show(x.replace(/(a)(b)?/, (m, p, q) => m + p + q)); }
out.push('s33' + " " + 'x.replace(/(a)(b)?/, (m, p, q) => m + p + q)' + " " + drive(s33, strings, stringArgs));
out.push('s33' + "'" + drive(s33, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s33' + "1" + driveOne(s33one, strings, stringArgs));
function s34(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.replaceAll("a", "b"))); } }
function s34one(x, y) { return show(x.replaceAll("a", "b")); }
out.push('s34' + " " + 'x.replaceAll("a", "b")' + " " + drive(s34, strings, stringArgs));
out.push('s34' + "'" + drive(s34, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s34' + "1" + driveOne(s34one, strings, stringArgs));
function s35(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.replaceAll(/a/g, "$$"))); } }
function s35one(x, y) { return show(x.replaceAll(/a/g, "$$")); }
out.push('s35' + " " + 'x.replaceAll(/a/g, "$$")' + " " + drive(s35, strings, stringArgs));
out.push('s35' + "'" + drive(s35, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s35' + "1" + driveOne(s35one, strings, stringArgs));
function s36(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.search(/b/))); } }
function s36one(x, y) { return show(x.search(/b/)); }
out.push('s36' + " " + 'x.search(/b/)' + " " + drive(s36, strings, stringArgs));
out.push('s36' + "'" + drive(s36, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s36' + "1" + driveOne(s36one, strings, stringArgs));
function s37(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.slice(y))); } }
function s37one(x, y) { return show(x.slice(y)); }
out.push('s37' + " " + 'x.slice(y)' + " " + drive(s37, strings, stringArgs));
out.push('s37' + "'" + drive(s37, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s37' + "1" + driveOne(s37one, strings, stringArgs));
function s38(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.slice(y, -2))); } }
function s38one(x, y) { return show(x.slice(y, -2)); }
out.push('s38' + " " + 'x.slice(y, -2)' + " " + drive(s38, strings, stringArgs));
out.push('s38' + "'" + drive(s38, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s38' + "1" + driveOne(s38one, strings, stringArgs));
function s39(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.slice(-3))); } }
function s39one(x, y) { return show(x.slice(-3)); }
out.push('s39' + " " + 'x.slice(-3)' + " " + drive(s39, strings, stringArgs));
out.push('s39' + "'" + drive(s39, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s39' + "1" + driveOne(s39one, strings, stringArgs));
function s40(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.split("X"))); } }
function s40one(x, y) { return show(x.split("X")); }
out.push('s40' + " " + 'x.split("X")' + " " + drive(s40, strings, stringArgs));
out.push('s40' + "'" + drive(s40, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s40' + "1" + driveOne(s40one, strings, stringArgs));
function s41(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.split(""))); } }
function s41one(x, y) { return show(x.split("")); }
out.push('s41' + " " + 'x.split("")' + " " + drive(s41, strings, stringArgs));
out.push('s41' + "'" + drive(s41, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s41' + "1" + driveOne(s41one, strings, stringArgs));
function s42(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.split("a", 2))); } }
function s42one(x, y) { return show(x.split("a", 2)); }
out.push('s42' + " " + 'x.split("a", 2)' + " " + drive(s42, strings, stringArgs));
out.push('s42' + "'" + drive(s42, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s42' + "1" + driveOne(s42one, strings, stringArgs));
function s43(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.split(/a|b/))); } }
function s43one(x, y) { return show(x.split(/a|b/)); }
out.push('s43' + " " + 'x.split(/a|b/)' + " " + drive(s43, strings, stringArgs));
out.push('s43' + "'" + drive(s43, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s43' + "1" + driveOne(s43one, strings, stringArgs));
function s44(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.split(y))); } }
function s44one(x, y) { return show(x.split(y)); }
out.push('s44' + " " + 'x.split(y)' + " " + drive(s44, strings, stringArgs));
out.push('s44' + "'" + drive(s44, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s44' + "1" + driveOne(s44one, strings, stringArgs));
function s45(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.substring(y))); } }
function s45one(x, y) { return show(x.substring(y)); }
out.push('s45' + " " + 'x.substring(y)' + " " + drive(s45, strings, stringArgs));
out.push('s45' + "'" + drive(s45, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s45' + "1" + driveOne(s45one, strings, stringArgs));
function s46(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.substring(y, 2))); } }
function s46one(x, y) { return show(x.substring(y, 2)); }
out.push('s46' + " " + 'x.substring(y, 2)' + " " + drive(s46, strings, stringArgs));
out.push('s46' + "'" + drive(s46, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s46' + "1" + driveOne(s46one, strings, stringArgs));
function s47(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.toLowerCase())); } }
function s47one(x, y) { return show(x.toLowerCase()); }
out.push('s47' + " " + 'x.toLowerCase()' + " " + drive(s47, strings, stringArgs));
out.push('s47' + "'" + drive(s47, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s47' + "1" + driveOne(s47one, strings, stringArgs));
function s48(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.toUpperCase())); } }
function s48one(x, y) { return show(x.toUpperCase()); }
out.push('s48' + " " + 'x.toUpperCase()' + " " + drive(s48, strings, stringArgs));
out.push('s48' + "'" + drive(s48, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s48' + "1" + driveOne(s48one, strings, stringArgs));
function s49(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.trim())); } }
function s49one(x, y) { return show(x.trim()); }
out.push('s49' + " " + 'x.trim()' + " " + drive(s49, strings, stringArgs));
out.push('s49' + "'" + drive(s49, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s49' + "1" + driveOne(s49one, strings, stringArgs));
function s50(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.trimEnd())); } }
function s50one(x, y) { return show(x.trimEnd()); }
out.push('s50' + " " + 'x.trimEnd()' + " " + drive(s50, strings, stringArgs));
out.push('s50' + "'" + drive(s50, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s50' + "1" + driveOne(s50one, strings, stringArgs));
function s51(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.trimStart())); } }
function s51one(x, y) { return show(x.trimStart()); }
out.push('s51' + " " + 'x.trimStart()' + " " + drive(s51, strings, stringArgs));
out.push('s51' + "'" + drive(s51, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s51' + "1" + driveOne(s51one, strings, stringArgs));
function s52(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(String(x))); } }
function s52one(x, y) { return show(String(x)); }
out.push('s52' + " " + 'String(x)' + " " + drive(s52, strings, stringArgs));
out.push('s52' + "'" + drive(s52, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s52' + "1" + driveOne(s52one, strings, stringArgs));
function s53(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.valueOf())); } }
function s53one(x, y) { return show(x.valueOf()); }
out.push('s53' + " " + 'x.valueOf()' + " " + drive(s53, strings, stringArgs));
out.push('s53' + "'" + drive(s53, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s53' + "1" + driveOne(s53one, strings, stringArgs));
function s54(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.toString())); } }
function s54one(x, y) { return show(x.toString()); }
out.push('s54' + " " + 'x.toString()' + " " + drive(s54, strings, stringArgs));
out.push('s54' + "'" + drive(s54, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s54' + "1" + driveOne(s54one, strings, stringArgs));
function s55(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(parseInt(x))); } }
function s55one(x, y) { return show(parseInt(x)); }
out.push('s55' + " " + 'parseInt(x)' + " " + drive(s55, strings, stringArgs));
out.push('s55' + "'" + drive(s55, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s55' + "1" + driveOne(s55one, strings, stringArgs));
function s56(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(parseInt(x, 16))); } }
function s56one(x, y) { return show(parseInt(x, 16)); }
out.push('s56' + " " + 'parseInt(x, 16)' + " " + drive(s56, strings, stringArgs));
out.push('s56' + "'" + drive(s56, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s56' + "1" + driveOne(s56one, strings, stringArgs));
function s57(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(Number.parseInt(x, 36))); } }
function s57one(x, y) { return show(Number.parseInt(x, 36)); }
out.push('s57' + " " + 'Number.parseInt(x, 36)' + " " + drive(s57, strings, stringArgs));
out.push('s57' + "'" + drive(s57, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s57' + "1" + driveOne(s57one, strings, stringArgs));
function s58(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(Number(x))); } }
function s58one(x, y) { return show(Number(x)); }
out.push('s58' + " " + 'Number(x)' + " " + drive(s58, strings, stringArgs));
out.push('s58' + "'" + drive(s58, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s58' + "1" + driveOne(s58one, strings, stringArgs));
function s59(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(Boolean(x))); } }
function s59one(x, y) { return show(Boolean(x)); }
out.push('s59' + " " + 'Boolean(x)' + " " + drive(s59, strings, stringArgs));
out.push('s59' + "'" + drive(s59, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s59' + "1" + driveOne(s59one, strings, stringArgs));
function s60(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(isNaN(x))); } }
function s60one(x, y) { return show(isNaN(x)); }
out.push('s60' + " " + 'isNaN(x)' + " " + drive(s60, strings, stringArgs));
out.push('s60' + "'" + drive(s60, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s60' + "1" + driveOne(s60one, strings, stringArgs));
function s61(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(isFinite(x))); } }
function s61one(x, y) { return show(isFinite(x)); }
out.push('s61' + " " + 'isFinite(x)' + " " + drive(s61, strings, stringArgs));
out.push('s61' + "'" + drive(s61, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s61' + "1" + driveOne(s61one, strings, stringArgs));
function s62(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x === "abc")); } }
function s62one(x, y) { return show(x === "abc"); }
out.push('s62' + " " + 'x === "abc"' + " " + drive(s62, strings, stringArgs));
out.push('s62' + "'" + drive(s62, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s62' + "1" + driveOne(s62one, strings, stringArgs));
function s63(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x === "")); } }
function s63one(x, y) { return show(x === ""); }
out.push('s63' + " " + 'x === ""' + " " + drive(s63, strings, stringArgs));
out.push('s63' + "'" + drive(s63, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s63' + "1" + driveOne(s63one, strings, stringArgs));
function s64(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x == "1e3")); } }
function s64one(x, y) { return show(x == "1e3"); }
out.push('s64' + " " + 'x == "1e3"' + " " + drive(s64, strings, stringArgs));
out.push('s64' + "'" + drive(s64, strings.slice().reverse(), stringArgs.slice(1)));
out.push('s64' + "1" + driveOne(s64one, strings, stringArgs));
function n0(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(Math.abs(x))); } }
function n0one(x, y) { return show(Math.abs(x)); }
out.push('n0' + " " + 'Math.abs(x)' + " " + drive(n0, numbers, numberArgs));
out.push('n0' + "'" + drive(n0, numbers.slice().reverse(), numberArgs.slice(1)));
out.push('n0' + "1" + driveOne(n0one, numbers, numberArgs));
function n1(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(Math.ceil(x))); } }
function n1one(x, y) { return show(Math.ceil(x)); }
out.push('n1' + " " + 'Math.ceil(x)' + " " + drive(n1, numbers, numberArgs));
out.push('n1' + "'" + drive(n1, numbers.slice().reverse(), numberArgs.slice(1)));
out.push('n1' + "1" + driveOne(n1one, numbers, numberArgs));
function n2(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(Math.floor(x))); } }
function n2one(x, y) { return show(Math.floor(x)); }
out.push('n2' + " " + 'Math.floor(x)' + " " + drive(n2, numbers, numberArgs));
out.push('n2' + "'" + drive(n2, numbers.slice().reverse(), numberArgs.slice(1)));
out.push('n2' + "1" + driveOne(n2one, numbers, numberArgs));
function n3(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(Math.round(x))); } }
function n3one(x, y) { return show(Math.round(x)); }
out.push('n3' + " " + 'Math.round(x)' + " " + drive(n3, numbers, numberArgs));
out.push('n3' + "'" + drive(n3, numbers.slice().reverse(), numberArgs.slice(1)));
out.push('n3' + "1" + driveOne(n3one, numbers, numberArgs));
function n4(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(Math.trunc(x))); } }
function n4one(x, y) { return show(Math.trunc(x)); }
out.push('n4' + " " + 'Math.trunc(x)' + " " + drive(n4, numbers, numberArgs));
out.push('n4' + "'" + drive(n4, numbers.slice().reverse(), numberArgs.slice(1)));
out.push('n4' + "1" + driveOne(n4one, numbers, numberArgs));
function n5(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(Math.sign(x))); } }
function n5one(x, y) { return show(Math.sign(x)); }
out.push('n5' + " " + 'Math.sign(x)' + " " + drive(n5, numbers, numberArgs));
out.push('n5' + "'" + drive(n5, numbers.slice().reverse(), numberArgs.slice(1)));
out.push('n5' + "1" + driveOne(n5one, numbers, numberArgs));
function n6(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(Math.sqrt(x))); } }
function n6one(x, y) { return show(Math.sqrt(x)); }
out.push('n6' + " " + 'Math.sqrt(x)' + " " + drive(n6, numbers, numberArgs));
out.push('n6' + "'" + drive(n6, numbers.slice().reverse(), numberArgs.slice(1)));
out.push('n6' + "1" + driveOne(n6one, numbers, numberArgs));
function n7(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(Math.fround(x))); } }
function n7one(x, y) { return show(Math.fround(x)); }
out.push('n7' + " " + 'Math.fround(x)' + " " + drive(n7, numbers, numberArgs));
out.push('n7' + "'" + drive(n7, numbers.slice().reverse(), numberArgs.slice(1)));
out.push('n7' + "1" + driveOne(n7one, numbers, numberArgs));
function n8(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(Math.clz32(x))); } }
function n8one(x, y) { return show(Math.clz32(x)); }
out.push('n8' + " " + 'Math.clz32(x)' + " " + drive(n8, numbers, numberArgs));
out.push('n8' + "'" + drive(n8, numbers.slice().reverse(), numberArgs.slice(1)));
out.push('n8' + "1" + driveOne(n8one, numbers, numberArgs));
function n9(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(Math.max(x, y))); } }
function n9one(x, y) { return show(Math.max(x, y)); }
out.push('n9' + " " + 'Math.max(x, y)' + " " + drive(n9, numbers, numberArgs));
out.push('n9' + "'" + drive(n9, numbers.slice().reverse(), numberArgs.slice(1)));
out.push('n9' + "1" + driveOne(n9one, numbers, numberArgs));
function n10(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(Math.min(x, y))); } }
function n10one(x, y) { return show(Math.min(x, y)); }
out.push('n10' + " " + 'Math.min(x, y)' + " " + drive(n10, numbers, numberArgs));
out.push('n10' + "'" + drive(n10, numbers.slice().reverse(), numberArgs.slice(1)));
out.push('n10' + "1" + driveOne(n10one, numbers, numberArgs));
function n11(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(Math.max(x, y, 0))); } }
function n11one(x, y) { return show(Math.max(x, y, 0)); }
out.push('n11' + " " + 'Math.max(x, y, 0)' + " " + drive(n11, numbers, numberArgs));
out.push('n11' + "'" + drive(n11, numbers.slice().reverse(), numberArgs.slice(1)));
out.push('n11' + "1" + driveOne(n11one, numbers, numberArgs));
function n12(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(Math.pow(x, y))); } }
function n12one(x, y) { return show(Math.pow(x, y)); }
out.push('n12' + " " + 'Math.pow(x, y)' + " " + drive(n12, numbers, numberArgs));
out.push('n12' + "'" + drive(n12, numbers.slice().reverse(), numberArgs.slice(1)));
out.push('n12' + "1" + driveOne(n12one, numbers, numberArgs));
function n13(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(Math.atan2(x, y))); } }
function n13one(x, y) { return show(Math.atan2(x, y)); }
out.push('n13' + " " + 'Math.atan2(x, y)' + " " + drive(n13, numbers, numberArgs));
out.push('n13' + "'" + drive(n13, numbers.slice().reverse(), numberArgs.slice(1)));
out.push('n13' + "1" + driveOne(n13one, numbers, numberArgs));
function n14(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(Math.imul(x, y))); } }
function n14one(x, y) { return show(Math.imul(x, y)); }
out.push('n14' + " " + 'Math.imul(x, y)' + " " + drive(n14, numbers, numberArgs));
out.push('n14' + "'" + drive(n14, numbers.slice().reverse(), numberArgs.slice(1)));
out.push('n14' + "1" + driveOne(n14one, numbers, numberArgs));
function n15(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(Number.isFinite(x))); } }
function n15one(x, y) { return show(Number.isFinite(x)); }
out.push('n15' + " " + 'Number.isFinite(x)' + " " + drive(n15, numbers, numberArgs));
out.push('n15' + "'" + drive(n15, numbers.slice().reverse(), numberArgs.slice(1)));
out.push('n15' + "1" + driveOne(n15one, numbers, numberArgs));
function n16(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(Number.isInteger(x))); } }
function n16one(x, y) { return show(Number.isInteger(x)); }
out.push('n16' + " " + 'Number.isInteger(x)' + " " + drive(n16, numbers, numberArgs));
out.push('n16' + "'" + drive(n16, numbers.slice().reverse(), numberArgs.slice(1)));
out.push('n16' + "1" + driveOne(n16one, numbers, numberArgs));
function n17(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(Number.isNaN(x))); } }
function n17one(x, y) { return show(Number.isNaN(x)); }
out.push('n17' + " " + 'Number.isNaN(x)' + " " + drive(n17, numbers, numberArgs));
out.push('n17' + "'" + drive(n17, numbers.slice().reverse(), numberArgs.slice(1)));
out.push('n17' + "1" + driveOne(n17one, numbers, numberArgs));
function n18(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(Number.isSafeInteger(x))); } }
function n18one(x, y) { return show(Number.isSafeInteger(x)); }
out.push('n18' + " " + 'Number.isSafeInteger(x)' + " " + drive(n18, numbers, numberArgs));
out.push('n18' + "'" + drive(n18, numbers.slice().reverse(), numberArgs.slice(1)));
out.push('n18' + "1" + driveOne(n18one, numbers, numberArgs));
function n19(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.toString())); } }
function n19one(x, y) { return show(x.toString()); }
out.push('n19' + " " + 'x.toString()' + " " + drive(n19, numbers, numberArgs));
out.push('n19' + "'" + drive(n19, numbers.slice().reverse(), numberArgs.slice(1)));
out.push('n19' + "1" + driveOne(n19one, numbers, numberArgs));
function n20(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.toString(2))); } }
function n20one(x, y) { return show(x.toString(2)); }
out.push('n20' + " " + 'x.toString(2)' + " " + drive(n20, numbers, numberArgs));
out.push('n20' + "'" + drive(n20, numbers.slice().reverse(), numberArgs.slice(1)));
out.push('n20' + "1" + driveOne(n20one, numbers, numberArgs));
function n21(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.toString(16))); } }
function n21one(x, y) { return show(x.toString(16)); }
out.push('n21' + " " + 'x.toString(16)' + " " + drive(n21, numbers, numberArgs));
out.push('n21' + "'" + drive(n21, numbers.slice().reverse(), numberArgs.slice(1)));
out.push('n21' + "1" + driveOne(n21one, numbers, numberArgs));
function n22(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.toString(36))); } }
function n22one(x, y) { return show(x.toString(36)); }
out.push('n22' + " " + 'x.toString(36)' + " " + drive(n22, numbers, numberArgs));
out.push('n22' + "'" + drive(n22, numbers.slice().reverse(), numberArgs.slice(1)));
out.push('n22' + "1" + driveOne(n22one, numbers, numberArgs));
function n23(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(Object.is(x, y))); } }
function n23one(x, y) { return show(Object.is(x, y)); }
out.push('n23' + " " + 'Object.is(x, y)' + " " + drive(n23, numbers, numberArgs));
out.push('n23' + "'" + drive(n23, numbers.slice().reverse(), numberArgs.slice(1)));
out.push('n23' + "1" + driveOne(n23one, numbers, numberArgs));
function n24(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(Number(x))); } }
function n24one(x, y) { return show(Number(x)); }
out.push('n24' + " " + 'Number(x)' + " " + drive(n24, numbers, numberArgs));
out.push('n24' + "'" + drive(n24, numbers.slice().reverse(), numberArgs.slice(1)));
out.push('n24' + "1" + driveOne(n24one, numbers, numberArgs));
function n25(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(String(x))); } }
function n25one(x, y) { return show(String(x)); }
out.push('n25' + " " + 'String(x)' + " " + drive(n25, numbers, numberArgs));
out.push('n25' + "'" + drive(n25, numbers.slice().reverse(), numberArgs.slice(1)));
out.push('n25' + "1" + driveOne(n25one, numbers, numberArgs));
function n26(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(Boolean(x))); } }
function n26one(x, y) { return show(Boolean(x)); }
out.push('n26' + " " + 'Boolean(x)' + " " + drive(n26, numbers, numberArgs));
out.push('n26' + "'" + drive(n26, numbers.slice().reverse(), numberArgs.slice(1)));
out.push('n26' + "1" + driveOne(n26one, numbers, numberArgs));
function n27(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(isNaN(x))); } }
function n27one(x, y) { return show(isNaN(x)); }
out.push('n27' + " " + 'isNaN(x)' + " " + drive(n27, numbers, numberArgs));
out.push('n27' + "'" + drive(n27, numbers.slice().reverse(), numberArgs.slice(1)));
out.push('n27' + "1" + driveOne(n27one, numbers, numberArgs));
function n28(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(isFinite(x))); } }
function n28one(x, y) { return show(isFinite(x)); }
out.push('n28' + " " + 'isFinite(x)' + " " + drive(n28, numbers, numberArgs));
out.push('n28' + "'" + drive(n28, numbers.slice().reverse(), numberArgs.slice(1)));
out.push('n28' + "1" + driveOne(n28one, numbers, numberArgs));
function n29(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(String.fromCharCode(x))); } }
function n29one(x, y) { return show(String.fromCharCode(x)); }
out.push('n29' + " " + 'String.fromCharCode(x)' + " " + drive(n29, numbers, numberArgs));
out.push('n29' + "'" + drive(n29, numbers.slice().reverse(), numberArgs.slice(1)));
out.push('n29' + "1" + driveOne(n29one, numbers, numberArgs));
function n30(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(parseInt(x))); } }
function n30one(x, y) { return show(parseInt(x)); }
out.push('n30' + " " + 'parseInt(x)' + " " + drive(n30, numbers, numberArgs));
out.push('n30' + "'" + drive(n30, numbers.slice().reverse(), numberArgs.slice(1)));
out.push('n30' + "1" + driveOne(n30one, numbers, numberArgs));
function n31(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x % y)); } }
function n31one(x, y) { return show(x % y); }
out.push('n31' + " " + 'x % y' + " " + drive(n31, numbers, numberArgs));
out.push('n31' + "'" + drive(n31, numbers.slice().reverse(), numberArgs.slice(1)));
out.push('n31' + "1" + driveOne(n31one, numbers, numberArgs));
function n32(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x | 0)); } }
function n32one(x, y) { return show(x | 0); }
out.push('n32' + " " + 'x | 0' + " " + drive(n32, numbers, numberArgs));
out.push('n32' + "'" + drive(n32, numbers.slice().reverse(), numberArgs.slice(1)));
out.push('n32' + "1" + driveOne(n32one, numbers, numberArgs));
function n33(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x >>> 0)); } }
function n33one(x, y) { return show(x >>> 0); }
out.push('n33' + " " + 'x >>> 0' + " " + drive(n33, numbers, numberArgs));
out.push('n33' + "'" + drive(n33, numbers.slice().reverse(), numberArgs.slice(1)));
out.push('n33' + "1" + driveOne(n33one, numbers, numberArgs));
function a0(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.at(1))); } }
function a0one(x, y) { return show(x.at(1)); }
out.push('a0' + " " + 'x.at(1)' + " " + drive(a0, arrays, arrayArgs));
out.push('a0' + "'" + drive(a0, arrays.slice().reverse(), arrayArgs.slice(1)));
out.push('a0' + "1" + driveOne(a0one, arrays, arrayArgs));
function a1(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.at(-1))); } }
function a1one(x, y) { return show(x.at(-1)); }
out.push('a1' + " " + 'x.at(-1)' + " " + drive(a1, arrays, arrayArgs));
out.push('a1' + "'" + drive(a1, arrays.slice().reverse(), arrayArgs.slice(1)));
out.push('a1' + "1" + driveOne(a1one, arrays, arrayArgs));
function a2(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.concat(y))); } }
function a2one(x, y) { return show(x.concat(y)); }
out.push('a2' + " " + 'x.concat(y)' + " " + drive(a2, arrays, arrayArgs));
out.push('a2' + "'" + drive(a2, arrays.slice().reverse(), arrayArgs.slice(1)));
out.push('a2' + "1" + driveOne(a2one, arrays, arrayArgs));
function a3(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.concat(1, [2, [3]]))); } }
function a3one(x, y) { return show(x.concat(1, [2, [3]])); }
out.push('a3' + " " + 'x.concat(1, [2, [3]])' + " " + drive(a3, arrays, arrayArgs));
out.push('a3' + "'" + drive(a3, arrays.slice().reverse(), arrayArgs.slice(1)));
out.push('a3' + "1" + driveOne(a3one, arrays, arrayArgs));
function a4(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.includes(2))); } }
function a4one(x, y) { return show(x.includes(2)); }
out.push('a4' + " " + 'x.includes(2)' + " " + drive(a4, arrays, arrayArgs));
out.push('a4' + "'" + drive(a4, arrays.slice().reverse(), arrayArgs.slice(1)));
out.push('a4' + "1" + driveOne(a4one, arrays, arrayArgs));
function a5(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.includes(NaN))); } }
function a5one(x, y) { return show(x.includes(NaN)); }
out.push('a5' + " " + 'x.includes(NaN)' + " " + drive(a5, arrays, arrayArgs));
out.push('a5' + "'" + drive(a5, arrays.slice().reverse(), arrayArgs.slice(1)));
out.push('a5' + "1" + driveOne(a5one, arrays, arrayArgs));
function a6(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.includes(undefined))); } }
function a6one(x, y) { return show(x.includes(undefined)); }
out.push('a6' + " " + 'x.includes(undefined)' + " " + drive(a6, arrays, arrayArgs));
out.push('a6' + "'" + drive(a6, arrays.slice().reverse(), arrayArgs.slice(1)));
out.push('a6' + "1" + driveOne(a6one, arrays, arrayArgs));
function a7(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.indexOf(2))); } }
function a7one(x, y) { return show(x.indexOf(2)); }
out.push('a7' + " " + 'x.indexOf(2)' + " " + drive(a7, arrays, arrayArgs));
out.push('a7' + "'" + drive(a7, arrays.slice().reverse(), arrayArgs.slice(1)));
out.push('a7' + "1" + driveOne(a7one, arrays, arrayArgs));
function a8(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.indexOf(NaN))); } }
function a8one(x, y) { return show(x.indexOf(NaN)); }
out.push('a8' + " " + 'x.indexOf(NaN)' + " " + drive(a8, arrays, arrayArgs));
out.push('a8' + "'" + drive(a8, arrays.slice().reverse(), arrayArgs.slice(1)));
out.push('a8' + "1" + driveOne(a8one, arrays, arrayArgs));
function a9(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.indexOf(-0))); } }
function a9one(x, y) { return show(x.indexOf(-0)); }
out.push('a9' + " " + 'x.indexOf(-0)' + " " + drive(a9, arrays, arrayArgs));
out.push('a9' + "'" + drive(a9, arrays.slice().reverse(), arrayArgs.slice(1)));
out.push('a9' + "1" + driveOne(a9one, arrays, arrayArgs));
function a10(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(Array.isArray(x))); } }
function a10one(x, y) { return show(Array.isArray(x)); }
out.push('a10' + " " + 'Array.isArray(x)' + " " + drive(a10, arrays, arrayArgs));
out.push('a10' + "'" + drive(a10, arrays.slice().reverse(), arrayArgs.slice(1)));
out.push('a10' + "1" + driveOne(a10one, arrays, arrayArgs));
function a11(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.join())); } }
function a11one(x, y) { return show(x.join()); }
out.push('a11' + " " + 'x.join()' + " " + drive(a11, arrays, arrayArgs));
out.push('a11' + "'" + drive(a11, arrays.slice().reverse(), arrayArgs.slice(1)));
out.push('a11' + "1" + driveOne(a11one, arrays, arrayArgs));
function a12(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.join("-"))); } }
function a12one(x, y) { return show(x.join("-")); }
out.push('a12' + " " + 'x.join("-")' + " " + drive(a12, arrays, arrayArgs));
out.push('a12' + "'" + drive(a12, arrays.slice().reverse(), arrayArgs.slice(1)));
out.push('a12' + "1" + driveOne(a12one, arrays, arrayArgs));
function a13(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.join(y))); } }
function a13one(x, y) { return show(x.join(y)); }
out.push('a13' + " " + 'x.join(y)' + " " + drive(a13, arrays, arrayArgs));
out.push('a13' + "'" + drive(a13, arrays.slice().reverse(), arrayArgs.slice(1)));
out.push('a13' + "1" + driveOne(a13one, arrays, arrayArgs));
function a14(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(copy(x).push(9, 8))); } }
function a14one(x, y) { return show(copy(x).push(9, 8)); }
out.push('a14' + " " + 'copy(x).push(9, 8)' + " " + drive(a14, arrays, arrayArgs));
out.push('a14' + "'" + drive(a14, arrays.slice().reverse(), arrayArgs.slice(1)));
out.push('a14' + "1" + driveOne(a14one, arrays, arrayArgs));
function a15(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(copy(x).pop())); } }
function a15one(x, y) { return show(copy(x).pop()); }
out.push('a15' + " " + 'copy(x).pop()' + " " + drive(a15, arrays, arrayArgs));
out.push('a15' + "'" + drive(a15, arrays.slice().reverse(), arrayArgs.slice(1)));
out.push('a15' + "1" + driveOne(a15one, arrays, arrayArgs));
function a16(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(copy(x).shift())); } }
function a16one(x, y) { return show(copy(x).shift()); }
out.push('a16' + " " + 'copy(x).shift()' + " " + drive(a16, arrays, arrayArgs));
out.push('a16' + "'" + drive(a16, arrays.slice().reverse(), arrayArgs.slice(1)));
out.push('a16' + "1" + driveOne(a16one, arrays, arrayArgs));
function a17(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(copy(x).unshift(0))); } }
function a17one(x, y) { return show(copy(x).unshift(0)); }
out.push('a17' + " " + 'copy(x).unshift(0)' + " " + drive(a17, arrays, arrayArgs));
out.push('a17' + "'" + drive(a17, arrays.slice().reverse(), arrayArgs.slice(1)));
out.push('a17' + "1" + driveOne(a17one, arrays, arrayArgs));
function a18(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(copy(x).splice(1, 1))); } }
function a18one(x, y) { return show(copy(x).splice(1, 1)); }
out.push('a18' + " " + 'copy(x).splice(1, 1)' + " " + drive(a18, arrays, arrayArgs));
out.push('a18' + "'" + drive(a18, arrays.slice().reverse(), arrayArgs.slice(1)));
out.push('a18' + "1" + driveOne(a18one, arrays, arrayArgs));
function a19(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(copy(x).splice(-1, 0, 7))); } }
function a19one(x, y) { return show(copy(x).splice(-1, 0, 7)); }
out.push('a19' + " " + 'copy(x).splice(-1, 0, 7)' + " " + drive(a19, arrays, arrayArgs));
out.push('a19' + "'" + drive(a19, arrays.slice().reverse(), arrayArgs.slice(1)));
out.push('a19' + "1" + driveOne(a19one, arrays, arrayArgs));
function a20(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.slice(1))); } }
function a20one(x, y) { return show(x.slice(1)); }
out.push('a20' + " " + 'x.slice(1)' + " " + drive(a20, arrays, arrayArgs));
out.push('a20' + "'" + drive(a20, arrays.slice().reverse(), arrayArgs.slice(1)));
out.push('a20' + "1" + driveOne(a20one, arrays, arrayArgs));
function a21(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.slice(-2))); } }
function a21one(x, y) { return show(x.slice(-2)); }
out.push('a21' + " " + 'x.slice(-2)' + " " + drive(a21, arrays, arrayArgs));
out.push('a21' + "'" + drive(a21, arrays.slice().reverse(), arrayArgs.slice(1)));
out.push('a21' + "1" + driveOne(a21one, arrays, arrayArgs));
function a22(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.slice(1, -1))); } }
function a22one(x, y) { return show(x.slice(1, -1)); }
out.push('a22' + " " + 'x.slice(1, -1)' + " " + drive(a22, arrays, arrayArgs));
out.push('a22' + "'" + drive(a22, arrays.slice().reverse(), arrayArgs.slice(1)));
out.push('a22' + "1" + driveOne(a22one, arrays, arrayArgs));
function a23(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(pushedAll(x))); } }
function a23one(x, y) { return show(pushedAll(x)); }
out.push('a23' + " " + 'pushedAll(x)' + " " + drive(a23, arrays, arrayArgs));
out.push('a23' + "'" + drive(a23, arrays.slice().reverse(), arrayArgs.slice(1)));
out.push('a23' + "1" + driveOne(a23one, arrays, arrayArgs));
function a24(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(poppedAll(x))); } }
function a24one(x, y) { return show(poppedAll(x)); }
out.push('a24' + " " + 'poppedAll(x)' + " " + drive(a24, arrays, arrayArgs));
out.push('a24' + "'" + drive(a24, arrays.slice().reverse(), arrayArgs.slice(1)));
out.push('a24' + "1" + driveOne(a24one, arrays, arrayArgs));
function c0(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(mapOps(x))); } }
function c0one(x, y) { return show(mapOps(x)); }
out.push('c0' + " " + 'mapOps(x)' + " " + drive(c0, keyCases, [0]));
out.push('c0' + "'" + drive(c0, keyCases.slice().reverse(), [0].slice(1)));
out.push('c0' + "1" + driveOne(c0one, keyCases, [0]));
function c1(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(setOps(x))); } }
function c1one(x, y) { return show(setOps(x)); }
out.push('c1' + " " + 'setOps(x)' + " " + drive(c1, keyCases, [0]));
out.push('c1' + "'" + drive(c1, keyCases.slice().reverse(), [0].slice(1)));
out.push('c1' + "1" + driveOne(c1one, keyCases, [0]));
function c2(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(weakOps(x))); } }
function c2one(x, y) { return show(weakOps(x)); }
out.push('c2' + " " + 'weakOps(x)' + " " + drive(c2, keyCases, [0]));
out.push('c2' + "'" + drive(c2, keyCases.slice().reverse(), [0].slice(1)));
out.push('c2' + "1" + driveOne(c2one, keyCases, [0]));
function d0(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.getFullYear())); } }
function d0one(x, y) { return show(x.getFullYear()); }
out.push('d0' + " " + 'x.getFullYear()' + " " + drive(d0, dates, [0]));
out.push('d0' + "'" + drive(d0, dates.slice().reverse(), [0].slice(1)));
out.push('d0' + "1" + driveOne(d0one, dates, [0]));
function d1(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.getMonth())); } }
function d1one(x, y) { return show(x.getMonth()); }
out.push('d1' + " " + 'x.getMonth()' + " " + drive(d1, dates, [0]));
out.push('d1' + "'" + drive(d1, dates.slice().reverse(), [0].slice(1)));
out.push('d1' + "1" + driveOne(d1one, dates, [0]));
function d2(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.getDate())); } }
function d2one(x, y) { return show(x.getDate()); }
out.push('d2' + " " + 'x.getDate()' + " " + drive(d2, dates, [0]));
out.push('d2' + "'" + drive(d2, dates.slice().reverse(), [0].slice(1)));
out.push('d2' + "1" + driveOne(d2one, dates, [0]));
function d3(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.getDay())); } }
function d3one(x, y) { return show(x.getDay()); }
out.push('d3' + " " + 'x.getDay()' + " " + drive(d3, dates, [0]));
out.push('d3' + "'" + drive(d3, dates.slice().reverse(), [0].slice(1)));
out.push('d3' + "1" + driveOne(d3one, dates, [0]));
function d4(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.getHours())); } }
function d4one(x, y) { return show(x.getHours()); }
out.push('d4' + " " + 'x.getHours()' + " " + drive(d4, dates, [0]));
out.push('d4' + "'" + drive(d4, dates.slice().reverse(), [0].slice(1)));
out.push('d4' + "1" + driveOne(d4one, dates, [0]));
function d5(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.getMinutes())); } }
function d5one(x, y) { return show(x.getMinutes()); }
out.push('d5' + " " + 'x.getMinutes()' + " " + drive(d5, dates, [0]));
out.push('d5' + "'" + drive(d5, dates.slice().reverse(), [0].slice(1)));
out.push('d5' + "1" + driveOne(d5one, dates, [0]));
function d6(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.getSeconds())); } }
function d6one(x, y) { return show(x.getSeconds()); }
out.push('d6' + " " + 'x.getSeconds()' + " " + drive(d6, dates, [0]));
out.push('d6' + "'" + drive(d6, dates.slice().reverse(), [0].slice(1)));
out.push('d6' + "1" + driveOne(d6one, dates, [0]));
function d7(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.getMilliseconds())); } }
function d7one(x, y) { return show(x.getMilliseconds()); }
out.push('d7' + " " + 'x.getMilliseconds()' + " " + drive(d7, dates, [0]));
out.push('d7' + "'" + drive(d7, dates.slice().reverse(), [0].slice(1)));
out.push('d7' + "1" + driveOne(d7one, dates, [0]));
function d8(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.getTime())); } }
function d8one(x, y) { return show(x.getTime()); }
out.push('d8' + " " + 'x.getTime()' + " " + drive(d8, dates, [0]));
out.push('d8' + "'" + drive(d8, dates.slice().reverse(), [0].slice(1)));
out.push('d8' + "1" + driveOne(d8one, dates, [0]));
function d9(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.getTimezoneOffset())); } }
function d9one(x, y) { return show(x.getTimezoneOffset()); }
out.push('d9' + " " + 'x.getTimezoneOffset()' + " " + drive(d9, dates, [0]));
out.push('d9' + "'" + drive(d9, dates.slice().reverse(), [0].slice(1)));
out.push('d9' + "1" + driveOne(d9one, dates, [0]));
function d10(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.getUTCFullYear())); } }
function d10one(x, y) { return show(x.getUTCFullYear()); }
out.push('d10' + " " + 'x.getUTCFullYear()' + " " + drive(d10, dates, [0]));
out.push('d10' + "'" + drive(d10, dates.slice().reverse(), [0].slice(1)));
out.push('d10' + "1" + driveOne(d10one, dates, [0]));
function d11(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.getUTCHours())); } }
function d11one(x, y) { return show(x.getUTCHours()); }
out.push('d11' + " " + 'x.getUTCHours()' + " " + drive(d11, dates, [0]));
out.push('d11' + "'" + drive(d11, dates.slice().reverse(), [0].slice(1)));
out.push('d11' + "1" + driveOne(d11one, dates, [0]));
function d12(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.getUTCMilliseconds())); } }
function d12one(x, y) { return show(x.getUTCMilliseconds()); }
out.push('d12' + " " + 'x.getUTCMilliseconds()' + " " + drive(d12, dates, [0]));
out.push('d12' + "'" + drive(d12, dates.slice().reverse(), [0].slice(1)));
out.push('d12' + "1" + driveOne(d12one, dates, [0]));
function d13(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(x.valueOf())); } }
function d13one(x, y) { return show(x.valueOf()); }
out.push('d13' + " " + 'x.valueOf()' + " " + drive(d13, dates, [0]));
out.push('d13' + "'" + drive(d13, dates.slice().reverse(), [0].slice(1)));
out.push('d13' + "1" + driveOne(d13one, dates, [0]));
function d14(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(typeof Date.now())); } }
function d14one(x, y) { return show(typeof Date.now()); }
out.push('d14' + " " + 'typeof Date.now()' + " " + drive(d14, dates, [0]));
out.push('d14' + "'" + drive(d14, dates.slice().reverse(), [0].slice(1)));
out.push('d14' + "1" + driveOne(d14one, dates, [0]));
function r0(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(regexpExec(x))); } }
function r0one(x, y) { return show(regexpExec(x)); }
out.push('r0' + " " + 'regexpExec(x)' + " " + drive(r0, regexps, [0]));
out.push('r0' + "'" + drive(r0, regexps.slice().reverse(), [0].slice(1)));
out.push('r0' + "1" + driveOne(r0one, regexps, [0]));
function r1(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(regexpTest(x))); } }
function r1one(x, y) { return show(regexpTest(x)); }
out.push('r1' + " " + 'regexpTest(x)' + " " + drive(r1, regexps, [0]));
out.push('r1' + "'" + drive(r1, regexps.slice().reverse(), [0].slice(1)));
out.push('r1' + "1" + driveOne(r1one, regexps, [0]));
function o0(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(Object.keys(x))); } }
function o0one(x, y) { return show(Object.keys(x)); }
out.push('o0' + " " + 'Object.keys(x)' + " " + drive(o0, objects, [0]));
out.push('o0' + "'" + drive(o0, objects.slice().reverse(), [0].slice(1)));
out.push('o0' + "1" + driveOne(o0one, objects, [0]));
function o1(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(Object.getOwnPropertyNames(x))); } }
function o1one(x, y) { return show(Object.getOwnPropertyNames(x)); }
out.push('o1' + " " + 'Object.getOwnPropertyNames(x)' + " " + drive(o1, objects, [0]));
out.push('o1' + "'" + drive(o1, objects.slice().reverse(), [0].slice(1)));
out.push('o1' + "1" + driveOne(o1one, objects, [0]));
function o2(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(Object.getOwnPropertySymbols(x).length)); } }
function o2one(x, y) { return show(Object.getOwnPropertySymbols(x).length); }
out.push('o2' + " " + 'Object.getOwnPropertySymbols(x).length' + " " + drive(o2, objects, [0]));
out.push('o2' + "'" + drive(o2, objects.slice().reverse(), [0].slice(1)));
out.push('o2' + "1" + driveOne(o2one, objects, [0]));
function o3(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(Object.assign({}, x))); } }
function o3one(x, y) { return show(Object.assign({}, x)); }
out.push('o3' + " " + 'Object.assign({}, x)' + " " + drive(o3, objects, [0]));
out.push('o3' + "'" + drive(o3, objects.slice().reverse(), [0].slice(1)));
out.push('o3' + "1" + driveOne(o3one, objects, [0]));
function o4(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(Object.getPrototypeOf(x) === Object.prototype)); } }
function o4one(x, y) { return show(Object.getPrototypeOf(x) === Object.prototype); }
out.push('o4' + " " + 'Object.getPrototypeOf(x) === Object.prototype' + " " + drive(o4, objects, [0]));
out.push('o4' + "'" + drive(o4, objects.slice().reverse(), [0].slice(1)));
out.push('o4' + "1" + driveOne(o4one, objects, [0]));
function o5(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(Reflect.getPrototypeOf(x) === null)); } }
function o5one(x, y) { return show(Reflect.getPrototypeOf(x) === null); }
out.push('o5' + " " + 'Reflect.getPrototypeOf(x) === null' + " " + drive(o5, objects, [0]));
out.push('o5' + "'" + drive(o5, objects.slice().reverse(), [0].slice(1)));
out.push('o5' + "1" + driveOne(o5one, objects, [0]));
function o6(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(Object.hasOwn(x, "a"))); } }
function o6one(x, y) { return show(Object.hasOwn(x, "a")); }
out.push('o6' + " " + 'Object.hasOwn(x, "a")' + " " + drive(o6, objects, [0]));
out.push('o6' + "'" + drive(o6, objects.slice().reverse(), [0].slice(1)));
out.push('o6' + "1" + driveOne(o6one, objects, [0]));
function o7(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(Object.hasOwn(x, "0"))); } }
function o7one(x, y) { return show(Object.hasOwn(x, "0")); }
out.push('o7' + " " + 'Object.hasOwn(x, "0")' + " " + drive(o7, objects, [0]));
out.push('o7' + "'" + drive(o7, objects.slice().reverse(), [0].slice(1)));
out.push('o7' + "1" + driveOne(o7one, objects, [0]));
function o8(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(Object.keys(Object.create(x)))); } }
function o8one(x, y) { return show(Object.keys(Object.create(x))); }
out.push('o8' + " " + 'Object.keys(Object.create(x))' + " " + drive(o8, objects, [0]));
out.push('o8' + "'" + drive(o8, objects.slice().reverse(), [0].slice(1)));
out.push('o8' + "1" + driveOne(o8one, objects, [0]));
function o9(xs, ys, from) { for (let i = from; i < xs.length; i++) { at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show(Math.random() < 1)); } }
function o9one(x, y) { return show(Math.random() < 1); }
out.push('o9' + " " + 'Math.random() < 1' + " " + drive(o9, objects, [0]));
out.push('o9' + "'" + drive(o9, objects.slice().reverse(), [0].slice(1)));
out.push('o9' + "1" + driveOne(o9one, objects, [0]));
console.log(out.join("\n"));
