#!/usr/bin/env python3
"""Writes builtins.mjs: every built-in that the AOT compiler has a fast path for (aot/AOTLowerBuiltins.cpp), called in a loop
over edge-case inputs. Each call is a function of its own, so each gets its own loop and its own types. Run the tests once as
they are and once with BUN_JSC_useAOTInlineFastPathsInLoops=0 (every operation compiled the compact way, as outside loops).

Usage: tests/aot/gen-builtins.py > tests/aot/builtins.mjs"""

STRING_CASES = [
    "x.at(y)", "x.charAt(y)", "x.charCodeAt(y)", "x.codePointAt(y)", "x.concat(y)", "x.concat(y, x)",
    'x.endsWith("a")', 'x.endsWith("\\n")', 'x.endsWith("abc")', "x.endsWith(y)", 'x.endsWith("a", y)',
    'x.startsWith("a")', 'x.startsWith("\\n")', 'x.startsWith("abc")', "x.startsWith(y)", 'x.startsWith("b", y)',
    'x.includes("a")', 'x.includes("X")', "x.includes(y)", 'x.includes("b", y)',
    'x.indexOf("a")', 'x.indexOf("\\n")', "x.indexOf(y)", 'x.indexOf("a", y)', 'x.lastIndexOf("a")', "x.lastIndexOf(y)", 'x.lastIndexOf("a", y)',
    'x.localeCompare("abc")', "x.localeCompare(y)", "x.match(/a+/g)", "x.match(/(b)(c)?/)", 'x.replace("a", "<$&>")', 'x.replace(/X/g, "-")',
    'x.replace(/(a)(b)?/, (m, p, q) => m + p + q)', 'x.replaceAll("a", "b")', 'x.replaceAll(/a/g, "$$")', "x.search(/b/)",
    "x.slice(y)", "x.slice(y, -2)", "x.slice(-3)", 'x.split("X")', 'x.split("")', 'x.split("a", 2)', "x.split(/a|b/)", "x.split(y)",
    "x.substring(y)", "x.substring(y, 2)", "x.toLowerCase()", "x.toUpperCase()", "x.trim()", "x.trimEnd()", "x.trimStart()",
    "String(x)", "x.valueOf()", "x.toString()", "parseInt(x)", "parseInt(x, 16)", "Number.parseInt(x, 36)", "Number(x)", "Boolean(x)",
    "isNaN(x)", "isFinite(x)", 'x === "abc"', 'x === ""', 'x == "1e3"',
]
NUMBER_CASES = [
    "Math.abs(x)", "Math.ceil(x)", "Math.floor(x)", "Math.round(x)", "Math.trunc(x)", "Math.sign(x)", "Math.sqrt(x)", "Math.fround(x)",
    "Math.clz32(x)", "Math.max(x, y)", "Math.min(x, y)", "Math.max(x, y, 0)", "Math.pow(x, y)", "Math.atan2(x, y)", "Math.imul(x, y)",
    "Number.isFinite(x)", "Number.isInteger(x)", "Number.isNaN(x)", "Number.isSafeInteger(x)", "x.toString()", "x.toString(2)",
    "x.toString(16)", "x.toString(36)", "Object.is(x, y)", "Number(x)", "String(x)", "Boolean(x)", "isNaN(x)", "isFinite(x)",
    "String.fromCharCode(x)", "parseInt(x)", "x % y", "x | 0", "x >>> 0",
]
ARRAY_CASES = [
    "x.at(1)", "x.at(-1)", "x.concat(y)", "x.concat(1, [2, [3]])", "x.includes(2)", "x.includes(NaN)", "x.includes(undefined)",
    "x.indexOf(2)", "x.indexOf(NaN)", "x.indexOf(-0)", "Array.isArray(x)", "x.join()", 'x.join("-")', "x.join(y)",
    "copy(x).push(9, 8)", "copy(x).pop()", "copy(x).shift()", "copy(x).unshift(0)", "copy(x).splice(1, 1)", "copy(x).splice(-1, 0, 7)",
    "x.slice(1)", "x.slice(-2)", "x.slice(1, -1)", "pushedAll(x)", "poppedAll(x)",
]
COLLECTION_CASES = [
    "mapOps(x)", "setOps(x)", "weakOps(x)",
]
DATE_CASES = [
    "x.getFullYear()", "x.getMonth()", "x.getDate()", "x.getDay()", "x.getHours()", "x.getMinutes()", "x.getSeconds()",
    "x.getMilliseconds()", "x.getTime()", "x.getTimezoneOffset()", "x.getUTCFullYear()", "x.getUTCHours()", "x.getUTCMilliseconds()",
    "x.valueOf()", "typeof Date.now()",
]
REGEXP_CASES = ["regexpExec(x)", "regexpTest(x)"]
OBJECT_CASES = [
    "Object.keys(x)", "Object.getOwnPropertyNames(x)", "Object.getOwnPropertySymbols(x).length", "Object.assign({}, x)",
    "Object.getPrototypeOf(x) === Object.prototype", "Reflect.getPrototypeOf(x) === null", 'Object.hasOwn(x, "a")', 'Object.hasOwn(x, "0")',
    "Object.keys(Object.create(x))", "Math.random() < 1",
]

PRELUDE = r"""// GENERATED by gen-builtins.py: built-ins with an AOT fast path, each in a loop of its own over edge-case inputs.
const out = [];
function show(v, depth = 0) {
	if (typeof v === "number") return Object.is(v, -0) ? "-0" : String(v);
	if (typeof v === "string") {
		if (v.length <= 40) return JSON.stringify(v);
		let h = 0;
		for (let i = 0; i < v.length; i++) h = (Math.imul(h, 31) + v.charCodeAt(i)) | 0;
		return `str(${v.length}:${h})`;
	}
	if (Array.isArray(v)) return depth > 2 ? "[...]" : "[" + v.slice(0, 12).map((e) => show(e, depth + 1)).join(",") + (v.length > 12 ? `,+${v.length - 12}` : "") + "]";
	if (v instanceof Map || v instanceof Set) return v.constructor.name + v.size;
	if (v && typeof v === "object") return depth > 2 ? "{...}" : "{" + Object.keys(v).slice(0, 8).map((k) => k + ":" + show(v[k], depth + 1)).join(",") + "}";
	return typeof v === "symbol" ? "sym" : String(v);
}
let at = 0;
let cells = [];
function drive(f, xs, ys) {
	cells = [];
	for (let from = 0; from < xs.length; ) {
		try {
			f(xs, ys, from);
			break;
		} catch (e) {
			cells.push("!" + e.constructor.name);
			from = at + 1;
		}
	}
	return cells.join(",");
}
function driveOne(f, xs, ys) {
	const r = [];
	for (let i = 0; i < xs.length; i++) {
		try {
			r.push(f(xs[i], ys[i % ys.length]));
		} catch (e) {
			r.push("!" + e.constructor.name);
		}
	}
	return r.join(",");
}
const copy = (a) => a.slice();
function pushedAll(a) { const b = []; for (const v of a) b.push(v); return b; }
function poppedAll(a) { const b = a.slice(); let n = 0; while (b.length) { b.pop(); n++; } return n; }
function lines(n) { let s = ""; for (let i = 1; i <= n; i++) s += i + "a\n"; return s; }
const flat = lines(14000); flat.split("\n");
const strings = ["", "a", "abc", "aXbXc", "ba", "héllo", "日本語", "\n", "a\n", lines(5), lines(14000), flat, flat.slice(3), flat.slice(0, 70000),
	"a".repeat(65534) + "\n", "a".repeat(65535) + "\n", "a".repeat(65536) + "\n", "b".repeat(70000) + "abc", "é".repeat(70000) + "a",
	" \t trim me \n", "UPPER lower İ ß", "1e3", "  42px", "0x1F", "-0", "123456789012345678901234567890", "Infinity", "zz"];
const stringArgs = [0, 1, -1, 2, 100, -100, NaN, undefined, 1.5, 65535, 70000, "1", "", "a", "X", "\n", "abc", "日", "b".repeat(100)];
const numbers = [0, -0, 1, -1, 1.5, -1.5, 2.5, -2.5, 0.49999999999999994, NaN, Infinity, -Infinity, 2 ** 31 - 1, 2 ** 31, -(2 ** 31),
	-(2 ** 31) - 1, 2 ** 32, 2 ** 53, 2 ** 53 + 2, 1e21, 5e-324, -5e-324, 1 / 3, 65, 0x10ffff, 3];
const numberArgs = [0, -0, 1, -1, 2, 0.5, NaN, Infinity, -Infinity, 2 ** 31, -3, 1e-7];
const holey = [1, , 3]; holey[10] = 4;
const arrays = [[], [1, 2, 3], [1.5, 2, NaN, -0], ["a", 2, undefined, null], holey, [[1], [2]], Array.from({ length: 70 }, (_, i) => i),
	new Array(5), [1, 2, 3].concat([4]), Object.freeze([2, 3]), ["x", "y"].map((s) => s + s)];
const arrayArgs = [[], [1], [[2]], ",", "", undefined, "-"];
const keyCases = [0, -0, NaN, "0", "a", "a".repeat(70000), {}, [], Symbol.iterator, null, undefined, 1.5, 2 ** 53];
function mapOps(k) {
	const m = new Map([[0, "zero"], ["a", "A"]]);
	m.set(k, 1); m.set(k, 2);
	return [m.get(k), m.has(k), m.get(-0), m.get(0), m.size, m.delete(k), m.has(k), m.size].map(show).join("/");
}
function setOps(k) {
	const s = new Set([0, "a"]);
	s.add(k); s.add(k);
	return [s.has(k), s.has(-0), s.size, s.delete(k), s.has(k), s.size].map(show).join("/");
}
function weakOps(k) {
	if (k === null || (typeof k !== "object" && typeof k !== "function")) return "prim";
	const wm = new WeakMap(), ws = new WeakSet();
	wm.set(k, 1); ws.add(k);
	return [wm.get(k), wm.has(k), ws.has(k), wm.delete(k), ws.delete(k), wm.has(k), ws.has(k)].map(show).join("/");
}
const dates = [new Date(0), new Date(-1), new Date(1e12 + 123), new Date(8.64e15), new Date(-8.64e15), new Date(NaN), new Date(2024, 1, 29, 23, 59, 59, 999),
	new Date("2026-03-29T01:30:00Z")];
const regexps = [/a/, /a/g, /a/y, /(\d+)/g, /^$/m, /é/u, /x*/g];
function regexpExec(r) { r.lastIndex = 0; const s = "a1a22aaa333é"; const found = []; for (let i = 0; i < 6; i++) { const m = r.exec(s); found.push(m ? m.index + ":" + m[0] : "null"); if (!m || !r.global && !r.sticky) break; } return found.join(";") + "|" + r.lastIndex; }
function regexpTest(r) { r.lastIndex = 0; const s = "xa1a"; const found = []; for (let i = 0; i < 4; i++) found.push(r.test(s), r.lastIndex); return found.join(";"); }
const objects = [{}, { a: 1, b: 2 }, Object.create(null), [1, 2], { 0: "z", a: undefined, [Symbol("s")]: 1 }, Object.assign(Object.create({ inherited: 1 }), { a: 3 }),
	new Map(), "str", Object.freeze({ a: 1 })];
"""


def emit(group, cases, inputs, args):
    lines = []
    for n, expr in enumerate(cases):
        name = f"{group}{n}"
        # No try in the loop (a try in a loop keeps the operations in it off their fast paths): drive() catches what is thrown
        # and goes on from the next input. And once outside any loop, in a function of its own.
        lines.append(f"function {name}(xs, ys, from) {{ for (let i = from; i < xs.length; i++) {{ at = i; const x = xs[i], y = ys[i % ys.length]; cells.push(show({expr})); }} }}")
        lines.append(f"function {name}one(x, y) {{ return show({expr}); }}")
        lines.append(f"out.push({name!r} + \" \" + {expr!r} + \" \" + drive({name}, {inputs}, {args}));")
        # Again with the inputs reversed and the arguments shifted: what the loop has seen first changes what it does.
        lines.append(f"out.push({name!r} + \"'\" + drive({name}, {inputs}.slice().reverse(), {args}.slice(1)));")
        lines.append(f"out.push({name!r} + \"1\" + driveOne({name}one, {inputs}, {args}));")
    return lines


body = []
body += emit("s", STRING_CASES, "strings", "stringArgs")
body += emit("n", NUMBER_CASES, "numbers", "numberArgs")
body += emit("a", ARRAY_CASES, "arrays", "arrayArgs")
body += emit("c", COLLECTION_CASES, "keyCases", "[0]")
body += emit("d", DATE_CASES, "dates", "[0]")
body += emit("r", REGEXP_CASES, "regexps", "[0]")
body += emit("o", OBJECT_CASES, "objects", "[0]")
print(PRELUDE + "\n".join(body) + '\nconsole.log(out.join("\\n"));')
